name: "Build and Push Docker Image to ECR"
description: "Composite action to build and push a Docker image to AWS ECR"

inputs:
  aws-region:
    description: "AWS region where ECR repository exists"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  ecr-repo:
    description: "Name of the ECR repository"
    required: true
  image-tag:
    description: "Tag for the Docker image"
    required: true
  dockerfile:
    description: "Path to the Dockerfile"
    default: "./Dockerfile"
  context:
    description: "Build context path"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ASIAXEFPMSBJEJGICZK7
        aws-secret-access-key: 7avdCoeZvxoDnzPaTG5AE9MzJYzOFTJITFrm2Z9q

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Docker image
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo }}:${{ inputs.image-tag }}
        echo "Building image: $IMAGE_URI"
        docker build -t $IMAGE_URI -f ${{ inputs.dockerfile }} ${{ inputs.context }}
        docker push $IMAGE_URI
        echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT
      shell: bash
