name: CI/CD Pipeline for Plaid Insights

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"   # Trigger only when index.html changes

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-image-tag
        run: echo "image-tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build, Push, and Deploy
        uses: ./.github/actions/docker-build-push
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          ecr-repo: my-app-repo
          image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
          dockerfile: ./Dockerfile
          context: .
          server-ip: ${{ secrets.SERVER_IP }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}

