name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Docker Image
        uses: ./.github/actions/docker-build-push
        with:
          aws-region: us-east-1
          aws-access-key-id: ASIAXEFPMSBJEJGICZK7
          aws-secret-access-key: 7avdCoeZvxoDnzPaTG5AE9MzJYzOFTJITFrm2Z9q
          ecr-repo: my-app-repo
          image-tag: ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .

