name: CI/CD Pipeline for Plaid Insights

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"   # Trigger only when index.html changes

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-image-tag
        run: echo "image-tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        uses: ./.github/actions/docker-build-push
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          ecr-repo: my-app-repo
          image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
          dockerfile: ./Dockerfile
          context: .

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Docker Image via SSM
        run: |
          IMAGE_TAG=${{ needs.build-and-push.outputs.image-tag }}
          aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy new Docker image" \
            --parameters 'commands=[
              "docker pull 489994096722.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:'$IMAGE_TAG'",
              "docker stop my-app || true && docker rm my-app || true",
              "docker run -d --name my-app -p 80:80 489994096722.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:'$IMAGE_TAG'"
            ]'

  



